[package]
name = "fixed-width"
version = "0.1.0"
edition = "2018"

[lib]
name = "fixed_width"
path = "src/lib.rs"

[[bin]]
name = "fixed_width_main"
path = "src/bin.rs"

[dependencies]
malachite-base = { path = "../malachite/malachite-base" }
